name = "nuclear"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "fc4aed1f47cc4a7f9df9c041fc08591e"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
MAIN_PAGE_URL = "https://siren.cloudaccess.host/"
PROXY_KV_URL = "https://siren.cloudaccess.host/best-latency.json"
